### ISSUE TITLE
Error while parsing a field of type DATE

### ISSUE THREAD

**Issue by demanuel** [CurtTilmes/perl6-dbpg#10]
Hello,

while doing a normal query (`select * from table`) with a field of type "date" with the value '05-FEB-18' (this is a valid value) i'm getting the error:

> 
> Invalid Date string '05-FEB-18'; use yyyy-mm-dd instead
>   in method convert at /home/ux992/.rakubrew/versions/moar-2020.01/share/perl6/site/sources/B7E6CB10751E19A4BAB058BCE45ED5888035CA33 (DB::Pg::Converter::DateTime) line 15
>   in code  at /home/ux992/.rakubrew/versions/moar-2020.01/share/perl6/site/sources/9840B92886D7BE2949AF97C3808E69D674F11F55 (DB::Pg::Results) line 50
>   in method row at /home/ux992/.rakubrew/versions/moar-2020.01/share/perl6/site/sources/9840B92886D7BE2949AF97C3808E69D674F11F55 (DB::Pg::Results) line 48
>   in method pull-one at /home/ux992/.rakubrew/versions/moar-2020.01/share/perl6/site/sources/9840B92886D7BE2949AF97C3808E69D674F11F55 (DB::Pg::Results) line 18
> 

'05-FEB-18' is a valid value as shown by:

```
=> select date '05-FEB-18' + integer '7';
 ?column?
-----------
 12-FEB-18
(1 row)
 
```

**Comment by CurtTilmes** [comment]
Postgresql has a `datestye` parameter which it uses to set the default style of dates.  You can run `show datestyle` to see your current datestyle.

Whichever datestyle you have configured for your database is incompatible with conversion of your dates to the Raku `DateTime` type (it can't figure out the century for your date of '18').

There are a number of ways to address this:

The easiest way would be to configure your whole database to use a compatible datestyle (I recommend 'iso' as the most modern/standard (See [xkcd PSA](https://xkcd.com/1179/))
You can do that with `alter database <your database> set datestyle to 'iso'`. Or edit your `postgresql.conf` and change the line for datestyle.

If there are other users/applications that depend on the current datestyle, you can set it just  for your client with `set datestyle to iso`, or by setting environment variable `PGDATESTYLE` to `iso`.

If other portions of your application won't allow even that, you could retrieve your datefields by converting to text, then convert the text to Raku's `DateTime` manually, or even replace the pluggable converter `DB::Pg::Converter::DateTime` with your own custom converter module and just pass it in to the connect and it will call your converter whenever it gets a date field.

**Comment by demanuel** [comment]
ok. I will follow your advice. Can you update the README with your update? I think it would be nice to have this information in a more visible place than in an issue.
