### ISSUE TITLE
Str instead of Hash on partial select

### ISSUE THREAD

**Issue by Altai-man** [CurtTilmes/perl6-dbpg#3]
Hello. Thanks for your module.

Routines `hashes` and `arrays` work great with select queries of type `SELECT *`, but when you need a partial result i.e. only certain columns, it becomes raw Str, like:
```
$pg.query("SELECT (id, user, foo) FROM foo").hashes;
```
will return e.g.
```
({row => (1, 2, 3)})
```
and the issue is that `row` value is a string of values with comma delimiter, instead of hash. So if data contains `,`, things become complicated.

The same issue occurs with `arrays`.

**Comment by CurtTilmes** [comment]
Your select statement includes extra parentheses that create a[ `ROW` constructor](https://www.postgresql.org/docs/10/static/sql-expressions.html#SQL-SYNTAX-ROW-CONSTRUCTORS).  The `ROW`  keyword is optional, but the parentheses make it act like this:
```SELECT ROW(id, user, foo) FROM foo```
which results in a composite value.  You could unpack that value, but, by default, as you noted, you just get back a `Str`.

If you just want a partial result, with only certain columns, just leave out the parens:

```$pg.query("SELECT id, user, foo FROM foo").hashes;```
